import ProjectDescription

let workspace = Workspace(
    name: "PathBridge",
    projects: ["."],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled
    )
)
